### ISSUE TITLE
Address already in use: JVM_Bind

### ISSUE THREAD

**Issue by kovac777** [PocketByte/LocoLaser#4]
Hello all!
When I try to start any localize gradle task, I get this error
`2018-07-30 10:03:15.885:INFO::Logging to STDERR via org.mortbay.log.StdErrLog
2018-07-30 10:03:15.886:INFO::jetty-6.1.x
2018-07-30 10:03:15.898:WARN::failed SocketConnector@127.0.0.1:8080: java.net.BindException: Address already in use: JVM_Bind
2018-07-30 10:03:15.899:WARN::failed Server@4d50efb8: java.net.BindException: Address already in use: JVM_Bind
2018-07-30 10:03:15.900:INFO::Stopped SocketConnector@127.0.0.1:8080
java.io.IOException: java.net.BindException: Address already in use: JVM_Bind
	at com.google.api.client.extensions.jetty.auth.oauth2.LocalServerReceiver.getRedirectUri(LocalServerReceiver.java:107)
	at com.google.api.client.extensions.java6.auth.oauth2.AuthorizationCodeInstalledApp.authorize(AuthorizationCodeInstalledApp.java:76)
	at ru.pocketbyte.locolaser.source.google.utils.OAuth2Helper.getCredential(OAuth2Helper.java:56)
	at ru.pocketbyte.locolaser.source.google.sheet.GoogleSheetConfig.prepareService(GoogleSheetConfig.java:114)
	at ru.pocketbyte.locolaser.source.google.sheet.GoogleSheetConfig.open(GoogleSheetConfig.java:42)
	at ru.pocketbyte.locolaser.source.google.sheet.GoogleSheetConfig.open(GoogleSheetConfig.java:28)
	at ru.pocketbyte.locolaser.LocoLaser.localizeInner(LocoLaser.java:72)
	at ru.pocketbyte.locolaser.LocoLaser.localize(LocoLaser.java:37)
	at ru.pocketbyte.locolaser.Main.main(Main.java:30)
Caused by: java.net.BindException: Address already in use: JVM_Bind
	at java.net.DualStackPlainSocketImpl.bind0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketBind(DualStackPlainSocketImpl.java:106)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
	at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:190)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at org.mortbay.jetty.bio.SocketConnector.newServerSocket(SocketConnector.java:80)
	at org.mortbay.jetty.bio.SocketConnector.open(SocketConnector.java:73)
	at org.mortbay.jetty.AbstractConnector.doStart(AbstractConnector.java:283)
	at org.mortbay.jetty.bio.SocketConnector.doStart(SocketConnector.java:147)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.Server.doStart(Server.java:235)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.api.client.extensions.jetty.auth.oauth2.LocalServerReceiver.getRedirectUri(LocalServerReceiver.java:104)
	... 8 more
`

How can I change port in configuration file or any other solutions?

**Comment by KamiSempai** [comment]
Artifact with fix already on JCenter. Build version 1.2.2
